# Build stage
FROM social-todo-service-cache AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o todoApp .

# Run stage
FROM alpine
WORKDIR /app
COPY --from=builder /app/todoApp .
EXPOSE 9090
ENTRYPOINT ["./todoApp"]
