version: '3.9'

services:
  mysql:
    image: mysql:8.0.32
    env_file:
      - ./db.env
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - todo-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./app.env
    environment:
      - ENV_FILE=app.env
    ports:
      - "${SERVER_PORT}:9090"
    depends_on:
      - mysql
    networks:
      - todo-network
    entrypoint: 
      [
        "/app/wait-for.sh",
        "mysql:3306",
        "--",
        "/app/start.sh"
      ]
    command: ["/app/todo-app"]

networks:
  todo-network:

volumes:
  mysql_data: